name: SonarCloud Analysis (Ghidra Java Only)

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar-analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Explorar a estrutura do repositório
      - name: Explore repository structure
        run: |
          echo "=== Estrutura do repositório ==="
          find . -type d -name "*Ghidra*" | sort
          echo "=== Conteúdo do diretório raiz ==="
          ls -la
          echo "=== Verificando se existem as pastas especificadas ==="
          [ -d "Ghidra/Framework/GhidraFramework" ] && echo "✓ GhidraFramework existe" || echo "✗ GhidraFramework NÃO existe"
          [ -d "Ghidra/Framework/SoftwareModeling" ] && echo "✓ SoftwareModeling existe" || echo "✗ SoftwareModeling NÃO existe"
          [ -d "Ghidra/Framework/Utility" ] && echo "✓ Utility existe" || echo "✗ Utility NÃO existe"

      # 3️⃣ Setup do Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      # 4️⃣ Cache do SonarCloud
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # 5️⃣ Análise SonarCloud com estrutura dinâmica
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=kepler4567_ghidra
            -Dsonar.organization=kepler4567
            -Dsonar.sources=.
            -Dsonar.inclusions=**/*.java
            -Dsonar.exclusions=**/test/**,**/Test/**,**/tests/**,**/Tests/**,**/*Test.java,**/*Tests.java
            -Dsonar.java.binaries=""
            -Dsonar.sourceEncoding=UTF-8
